language: php

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# php compatibility
php:
  - "7.2"
  - "7.3"
  - "7.4snapshot"

matrix:
  allow_failures:
    - php: "7.4snapshot"

cache:
  - directories:
    - $HOME/.composer

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer install --no-interaction --prefer-dist
  - mkdir -p build

script:
  - vendor/bin/phplint
  - vendor/bin/php-cs-fixer fix --verbose --dry-run
  - vendor/bin/phpcs --colors -sp src/ tests/
  - vendor/bin/phpunit --testdox --verbose
  - vendor/bin/phpstan.phar analyse --no-progress --verbose --level max src/ tests/

notifications:
  email: false
